opsclick/urls.py
from __future__ import unicode_literals

from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.i18n import set_language

from mezzanine.core.views import direct_to_template
from mezzanine.conf import settings

from sitemaps import *
import views

admin.autodiscover()

sitemaps = {
    'blogs': BlogSitemap(),
    'static': StaticPagesSitemap(),
}

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = i18n_patterns(
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    url("^admin/", include(admin.site.urls)),
)

if settings.USE_MODELTRANSLATION:
    urlpatterns += [
        url('^i18n/$', set_language, name='set_language'),
    ]

urlpatterns += [
    url('^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps':sitemaps}),
    url('^robots\.txt', include('robots.urls')),

    url("^$", direct_to_template, {"template": "index.html"}, name="home"),
    url(r'^accounts/', include('allauth.urls')),
    
    url(r"^platform", direct_to_template, {"template": "platform.html"}, name="platform"),
    url(r"^services", direct_to_template, {"template": "services.html"}, name="services"),
    url(r"^university", direct_to_template, {"template": "university.html"}, name="university"),
    url(r"^videos", direct_to_template, {"template": "videos.html"}, name="videos"),
    # url(r"^news", direct_to_template, {"template": "news.html"}, name="news"),
    url(r"^learn-more", direct_to_template, {"template": "learn-more.html"}, name="learn-more"),
    url(r"^webinar_sign_up", views.webinar_sign_up, name="webinar_sign_up"),
    url(r"^verify/(?P<key>.*)/", views.verify_webinar, name="verify_webinar"),
    url(r"^submit_resume", views.submit_resume, name="submit_resume"),

    url("^", include("mezzanine.urls")),
]

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

sign_up/models.py
from __future__ import unicode_literals

from django.db import models

class OpsUser(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    genre = models.CharField(max_length=10)
    experience = models.IntegerField(default=0)
    zipcode = models.CharField(max_length=20)
    phone = models.CharField(max_length=20)
    resume = models.FileField(upload_to='resume', null=True, blank=True)
    verified = models.BooleanField(default=False)
    vkey = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)

opsclick/views.py
import os
import hashlib
import base64
import mimetypes

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import send_mail
from django.conf import settings
from django.utils.encoding import smart_str
from wsgiref.util import FileWrapper
from django.views.decorators.csrf import csrf_exempt

from sign_up.models import *


genre_key_code = {
    'webinar': '@3$',
    'reference': '%7!',
    'execsummary': '9$%',
    'resume': '6^&'
}

def platform(request):
    return render(request, 'platform.html')


@csrf_exempt
def webinar_sign_up(request):
    """
    view for webinar, reference, resume
    """
    first_name, last_name, email, genre = parse_request(request)
    user = OpsUser.objects.filter(email=email, genre=genre).first()
    if user:
        if user.first_name == first_name and user.last_name == last_name:
            return HttpResponse('You are already registered!', 200)        
        return HttpResponse('The email is already used!', status=405)
    else:
        # verification key
        key = base64.b64encode(hashlib.new('md5').digest())
        # set genre in the key
        key = "{}{}{}".format(key[:5], genre_key_code[genre], key[5:])

        user = OpsUser.objects.create(first_name=first_name, last_name=last_name, 
                               genre=genre, email=email, vkey=key)

        if genre == 'resume':
            user.experience = request.POST.get('experience')
            user.zipcode = request.POST.get('zipcode')
            user.phone = request.POST.get('phone')
            user.resume = request.FILES.get('resume')
            user.save()

        # send verification email
        email_subject = 'Please Confirm Your E-mail Address'

        email_body = 'Dear Customer.\n\nYou are receiving this e-mail because '+\
                     'user {} at www.opsclick.com has given yours as '+\
                     'an e-mail address to connect their account.\n'+\
                     'To confirm this is correct, go to http://localhost:8000/verify/{}/\n\n'+\
                     'Thank you!\n'+\
                     'www.opsclick.com'
        email_body = email_body.format(first_name+' '+last_name, key)

        send_mail(email_subject, email_body, settings.DEFAULT_FROM_EMAIL, [email], 
                  fail_silently=False)        

        return HttpResponse('We have sent an e-mail to you for verification. ' + 
                            'Follow the link provided to finalize the signup ' +
                            'process. Please contact us if you do not receive ' +
                            'it within a few minutes.', 201)


def verify_webinar(request, key):
    """
    email verification for webinar, reference, resume
    """
    user = OpsUser.objects.filter(vkey=key).first()
    if user:        
        user.verified = True
        user.save()

        if key[5:8] in [genre_key_code['webinar'], genre_key_code['resume']]: # webinar
            return HttpResponse('You are successfully signed up!\n Thank you.')
        else:            
            path = smart_str(settings.PROJECT_ROOT+'/OpsClick_QuickReferenceGuide.pdf')
            if key[5:8] == genre_key_code['execsummary']:
                path = smart_str(settings.PROJECT_ROOT+'/OpsClick_ExecSummary.pdf')
            wrapper = FileWrapper( open( path, "r" ) )
            content_type = mimetypes.guess_type( path )[0]

            response = HttpResponse(wrapper, content_type = content_type)
            response['Content-Length'] = os.path.getsize( path ) # not FileField instance
            response['Content-Disposition'] = 'attachment; filename=%s/' % smart_str( os.path.basename( path ) ) # same here

            return response
    return HttpResponse('Wrong verification key!')


def parse_request(request):
    first_name = request.POST.get('first_name')
    last_name = request.POST.get('last_name')
    email = request.POST.get('email')
    genre = request.POST.get('genre')
    return first_name, last_name, email, genre


def submit_resume(request):
    if request.method == 'GET':
        return render(request, 'submit_resume.html')

sign_up/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!doctype html>
<html lang="{{ LANGUAGE_CODE }}"{% if LANGUAGE_BIDI %} dir="rtl"{% endif %}>
{% load pages_tags mezzanine_tags i18n staticfiles %}

<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="{% block meta_keywords %}{% endblock %}">
<meta name="description" content="{% block meta_description %}{% endblock %}">
<title>OpsClick</title>
<link rel="shortcut icon" href="{% static "img/Fav_opsclick.ico" %}">

{% ifinstalled mezzanine.blog %}
<link rel="alternate" type="application/rss+xml" title="RSS" href="{% url "blog_post_feed" "rss" %}">
<link rel="alternate" type="application/atom+xml" title="Atom" href="{% url "blog_post_feed" "atom" %}">
{% endifinstalled %}

{% compress css %}
<link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
<link rel="stylesheet" href="{% static "css/mezzanine.css" %}">
<link rel="stylesheet" href="{% static "css/bootstrap-theme.css" %}">
{% if LANGUAGE_BIDI %}
<link rel="stylesheet" href="{% static "css/bootstrap-rtl.css" %}">
{% endif %}
{% ifinstalled cartridge.shop %}
<link rel="stylesheet" href="{% static "css/cartridge.css" %}">
{% if LANGUAGE_BIDI %}
<link rel="stylesheet" href="{% static "css/cartridge.rtl.css" %}">
{% endif %}
{% endifinstalled %}
{% block extra_css %}{% endblock %}
{% endcompress %}
<link rel="stylesheet" href="{% static "css/styles.css" %}">

{% compress js %}
<script src="{% static "mezzanine/js/"|add:settings.JQUERY_FILENAME %}"></script>
<script src="{% static "js/bootstrap.js" %}"></script>
<script src="{% static "js/bootstrap-extras.js" %}"></script>
{% block extra_js %}{% endblock %}
{% endcompress %}

<!--[if lt IE 9]>
<script src="{% static "js/html5shiv.js" %}"></script>
<script src="{% static "js/respond.min.js" %}"></script>
<![endif]-->

{% block extra_head %}{% endblock %}
</head>

<body id="{% block body_id %}body{% endblock %}">

<div class="navbar navbar-default navbar-fixed-top" role="navigation">
<div class="container">
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">{% trans "Toggle Navigation" %}</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    {% block navbar_title %}
    {% if settings.SITE_TITLE %}<a class="navbar-brand" href="/"><img class="logo" src="/static/img/logo.png"></a>{% endif %}
    {% endblock%}
</div>
<div class="navbar-collapse collapse">
    {% block navbar_dropdown_menu %}
        {#% page_menu "pages/menus/dropdown.html" %#}
    <ul class="nav navbar-nav">
        <li id="dropdown-menu-home"><a href="/">Home</a></li>
<!--         <li class="dropdown" id="#about-us"><a href="/#about-us" class="dropdown-toggle disabled" data-toggle="dropdown">
                About Us
                <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li class="
                   " id="#core-philosophy"><a href="/#core-philosophy" class="disabled-link">Core Philosophy</a></li>
                <li class="
                   " id="#management"><a href="/#management" class="disabled-link">Management</a></li>
                <li class="
                   " id="#investors"><a href="/#investors" class="disabled-link">Investors</a></li>
                <li class="
                   " id="#locations"><a href="/#locations">Locations</a></li>
            </ul>
        </li>
        <li class="dropdown
                   " id="#partners"><a href="/#partners" class="dropdown-toggle disabled" data-toggle="dropdown">
                Partners
                <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li class="
                   " id="#partner-program"><a href="/#partner-program" class="disabled-link">Partner Program</a></li>
                <li class="
                   " id="#apply-now"><a href="/#apply-now" class="disabled-link">Become a Partner</a></li>
            </ul>
        </li> -->
        <li class="dropdown
                   " id="#careers"><a href="/#careers" class="dropdown-toggle disabled" data-toggle="dropdown">
                Careers
                <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li class="
                   " id="#find-jobs"><a href="/#find-jobs" class="disabled-link">Find Jobs</a></li>
                <li class="
                   " id="#submit-resume"><a href="/submit_resume">Submit Resume</a></li>
            </ul>
        </li>
        <li class="
                   " id="-learn-more"><a href="/learn-more">
                Learn More</a></li>
    </ul>
    {% endblock%}

    <ul class="nav navbar-nav navbar-right">    
        <li><a href='/accounts/signup' class="navbar-right _p46">Schedule a demo</a></li>
        <li>
            <a href="mailto:sales@opsclick.com" class="email-btn _p46" style="padding:2px 6px;">
                <img src="/static/img/mail.png" style="width:18px;">
            </a>
        </li>
        <li class="dropdown">
            <a href='#id_follow_us' class="navbar-right dropdown-toggle disabled _p46" data-toggle="dropdown"><img src="/static/img/phone.png" style="width:20px;"></a>
            <ul class="dropdown-menu" style="min-width: 138px;">
                <li style="float:left;margin-left: 10px;">
                    (202) 640-8868
                </li>
            </ul>
        </li>
        <li>
            <a target="_blank" href="https://www.facebook.com/pages/opsclick/167097030415794" class="fb-btn _p46" style="padding:2px 6px;">
                <img src="/static/img/facebook.png" style="width:20px;">
            </a>
        </li>
        <li>
            <a target="_blank" href="https://twitter.com/ops_click" class="twit-btn _p46" style="padding:2px 6px;">
                <img src="/static/img/twitter.png" style="width:20px;">
            </a>
        </li>
        <li>
            <a target="_blank" href="https://www.linkedin.com/company/opsclick" class="linkedin-btn _p46" style="padding:2px 6px;">
                <img src="/static/img/linkedin.png" style="width:20px;">
            </a>
        </li>
        
        {% if request.user.is_authenticated %}
        <li class="dropdown" id="#"><a href="/" class="dropdown-toggle disabled _p46" data-toggle="dropdown">
            {{ request.user.email }}
            <b class="caret"></b></a><ul class="dropdown-menu"><li class="
               " id="#"><a href="/accounts/logout">Sign Out</a></li></ul></li>        
        {% else %}
        {% endif %}
    </ul>
    {% block navbar_search_form %}
    {% endblock %}
</div>
</div>
</div>

{% block index_main %}
{% endblock %}

<div class="container" style="padding-top: 20px;">
    {% block main %}
    {% endblock %}
</div>


<div class="navbar navbar-default" role="navigation" style="margin-bottom: 0;">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/"><img class="logo" src="/static/img/logo.png"></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
<!--                 <li class="" id="dropdown-menu-legal"><a href="/legal/">Legal</a></li>                
                <li class="" id="learn-more"><a href="/support-terms/">Support Terms</a></li>
                <li class="" id="learn-more"><a href="javascript:void(0);">Follow Us</a></li>
 -->                <li><a target="_blank" href="https://www.facebook.com/pages/opsclick/167097030415794" class="fb-btn"><img src="/static/img/facebook.png" style="width:20px;"></a></li>
                <li><a target="_blank" href="https://twitter.com/ops_click" class="twit-btn">
                    <img src="/static/img/twitter.png" style="width:20px;">
                </a></li>
                <li><a target="_blank" href="https://www.linkedin.com/company/opsclick" class="linkedin-btn">
                    <img src="/static/img/linkedin.png" style="width:20px;">
                </a></li>
                <li><a href="mailto:sales@opsclick.com" class="email-btn">
                    <img src="/static/img/mail.png" style="height: 18px;">
                </a></li>
            </ul>
        </div>
    </div>
</div>

{% block footer_js %}
{% include "includes/footer_scripts.html" %}
{% endblock %}

<script type="text/javascript" src="/static/js/opsclick.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-86983824-1', 'auto');
  ga('send', 'pageview');

</script>

</body>
</html>

templates/blog/blog_post_detail.html
{% load mezzanine_tags i18n %}

{% block main %}

{% block blog_post_detail_content %}
{% editable blog_post.content %}
{{ blog_post.content|richtext_filters|safe }}
{% endeditable %}
{% endblock %}

{% endblock %}

templates/blog/blog_post_detail_full.html
{% extends "blog/blog_post_list.html" %}
{% load mezzanine_tags comment_tags keyword_tags rating_tags i18n disqus_tags %}

{% block meta_title %}{{ blog_post.meta_title }}{% endblock %}

{% block meta_keywords %}{% metablock %}
{% keywords_for blog_post as tags %}
{% for tag in tags %}{% if not forloop.first %}, {% endif %}{{ tag }}{% endfor %}
{% endmetablock %}{% endblock %}

{% block meta_description %}{% metablock %}
{{ blog_post.description }}
{% endmetablock %}{% endblock %}

{% block title %}
{% editable blog_post.title %}{{ blog_post.title }}{% endeditable %}
{% endblock %}

{% block breadcrumb_menu %}
{{ block.super }}
<li class="active">{{ blog_post.title }}</li>
{% endblock %}

{% block main %}
{% block blog_post_previous_next %}
<ul class="pager">
{% with blog_post.get_previous_by_publish_date as previous %}
{% if previous %}
<li class="previous">
    <a href="{{ previous.get_absolute_url }}">&larr; {{ previous }}</a>
</li>
{% endif %}
{% endwith %}
{% with blog_post.get_next_by_publish_date as next %}
{% if next %}
<li class="next">
    <a href="{{ next.get_absolute_url }}">{{ next }} &rarr;</a>
</li>
{% endif %}
{% endwith %}
</ul>
{% endblock %}

{% editable blog_post.title %}<h2 style="padding: 5px 0;">{{ blog_post.title }}</h2>{% endeditable %}

{% block blog_post_detail_featured_image %}
{% if settings.BLOG_USE_FEATURED_IMAGE and blog_post.featured_image %}
<p><img class="img-responsive" src="{{ MEDIA_URL }}{% thumbnail blog_post.featured_image 600 0 %}"></p>
{% endif %}
{% endblock %}

{% if settings.COMMENTS_DISQUS_SHORTNAME %}
{% include "generic/includes/disqus_counts.html" %}
{% endif %}

{% block blog_post_detail_content %}
{% editable blog_post.content %}
{{ blog_post.content|richtext_filters|safe }}
{% endeditable %}
{% endblock %}

{% block blog_post_detail_keywords %}
{% keywords_for blog_post as tags %}
{% if tags %}
{% spaceless %}
<ul class="list-inline tags">
    <li>{% trans "Tags" %}:</li>
    {% for tag in tags %}
    <li><a href="{% url "blog_post_list_tag" tag.slug %}">{{ tag }}</a>{% if not forloop.last %}, {% endif %}</li>
    {% endfor %}
</ul>
{% endspaceless %}
{% endif %}
{% endblock %}

{% block blog_post_detail_rating %}
<div class="panel panel-default rating">
    <div class="panel-body">
    {% rating_for blog_post %}
    </div>
</div>
{% endblock %}

{% block blog_post_detail_sharebuttons %}
{% set_short_url_for blog_post %}
<a class="btn btn-sm share-twitter" target="_blank" href="http://twitter.com/home?status={{ blog_post.short_url|urlencode }}%20{{ blog_post.title|urlencode }}">{% trans "Share on Twitter" %}</a>
<a class="btn btn-sm share-facebook" target="_blank" href="http://facebook.com/sharer.php?u={{ request.build_absolute_uri }}&amp;t={{ blog_post.title|urlencode }}">{% trans "Share on Facebook" %}</a>
{% endblock %}

{% block blog_post_detail_postedby %}
{% editable blog_post.publish_date %}
<h6 class="post-meta">
    {% trans "Posted by" %}:
    {% with blog_post.user as author %}
    <a href="{% url "blog_post_list_author" author %}">{{ author.get_full_name|default:author.username }}</a>
    {% endwith %}
    {% blocktrans with sometime=blog_post.publish_date|timesince %}{{ sometime }} ago{% endblocktrans %}
</h6>
{% endeditable %}
{% endblock %}
{% block blog_post_detail_commentlink %}
<p>
    {% if blog_post.allow_comments %}
        {% if settings.COMMENTS_DISQUS_SHORTNAME %}
            (<a href="{{ blog_post.get_absolute_url }}#disqus_thread"
                data-disqus-identifier="{% disqus_id_for blog_post %}">{% spaceless %}
                {% trans "Comments" %}
            {% endspaceless %}</a>)
        {% else %}(<a href="#comments">{% spaceless %}
            {% blocktrans count comments_count=blog_post.comments_count %}{{ comments_count }} comment{% plural %}{{ comments_count }} comments{% endblocktrans %}
            {% endspaceless %}</a>)
        {% endif %}
    {% endif %}
</p>
{% endblock %}

{% block blog_post_detail_related_posts %}
{% if related_posts %}
<div id="related-posts">
<h3>{% trans 'Related posts' %}</h3>
<ul class="list-unstyled">
{% for post in related_posts %}
     <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
{% endfor %}
</ul>
</div>
{% endif %}
{% endblock %}

{% block blog_post_detail_comments %}
{% if blog_post.allow_comments %}{% comments_for blog_post %}{% endif %}
{% endblock %}

{% endblock %}

templates/blog/includes/filter_panel.html
{% load blog_tags keyword_tags mezzanine_tags i18n %}

{% block blog_recent_posts %}
{% blog_recent_posts 5 as recent_posts %}
{% if recent_posts %}
<h3>{% trans "Recent Posts" %}</h3>
<ul class="list-unstyled recent-posts">
{% for recent_post in recent_posts %}
<li>
    {% spaceless %}
    <a href="{{ recent_post.get_absolute_url }}">
        {% if settings.BLOG_USE_FEATURED_IMAGE and recent_post.featured_image %}
        <img src="{{ MEDIA_URL }}{% thumbnail recent_post.featured_image 24 24 %}">
        {% endif %}
    {{ recent_post.title }}
    </a>
    {% endspaceless %}
</li>
{% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block blog_months %}
{% blog_months as months %}
{% if months %}
<h3>{% trans "Archive" %}</h3>
{% for month in months %}
    {% ifchanged month.date.year %}
        {% if not forloop.first %}</ul>{% endif %}
        <h6>{{ month.date.year }}</h6><ul class="list-unstyled">
    {% endifchanged %}
    <li><a href="{% url "blog_post_list_month" year=month.date.year month=month.date.month %}"
        >{{ month.date|date:"F" }}</a> ({{ month.post_count }})</li>
{% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block blog_categories %}
{% blog_categories as categories %}
{% if categories %}
<h3>{% trans "Categories" %}</h3>
<ul class="list-unstyled">
{% for category in categories %}
<li><a href="{% url "blog_post_list_category" category.slug %}"
    >{{ category }}</a> ({{ category.post_count }})</li>
{% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block blog_keywords %}
{% keywords_for blog.blogpost as tags %}
{% if tags %}
<h3>{% trans "Tags" %}</h3>
<ul class="list-inline tag-cloud">
{% for tag in tags %}
<li>
    <a href="{% url "blog_post_list_tag" tag.slug %}"
        class="tag-weight-{{ tag.weight }}">{{ tag }}</a>
    ({{ tag.item_count }})
</li>
{% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block blog_authors %}
{% blog_authors as authors %}
{% if authors %}
<h3>{% trans "Authors" %}</h3>
<ul class="list-unstyled">
{% for author in authors %}
    <li><a href="{% url "blog_post_list_author" author.username %}"
        >{{ author.get_full_name|default:author.username }}</a>
        ({{ author.post_count }})</li>
{% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block blog_feeds %}
<h3>{% trans "Feeds" %}</h3>
{% if tag %}
    <a href="{% url "blog_post_feed_tag" tag.slug "rss" %}">{% trans "RSS" %}</a> /
    <a href="{% url "blog_post_feed_tag" tag.slug "atom" %}">{% trans "Atom" %}</a>
{% endif %}
{% if category %}
    <a href="{% url "blog_post_feed_category" category.slug "rss" %}">{% trans "RSS" %}</a> /
    <a href="{% url "blog_post_feed_category" category.slug "atom" %}">{% trans "Atom" %}</a>
{% endif %}
{% if author %}
    <a href="{% url "blog_post_feed_author" author.username "rss" %}">{% trans "RSS" %}</a> /
    <a href="{% url "blog_post_feed_author" author.username "atom" %}">{% trans "Atom" %}</a>
{% endif %}
{% if not tag and not category and not author %}
    <a href="{% url "blog_post_feed" "rss" %}">{% trans "RSS" %}</a> /
    <a href="{% url "blog_post_feed" "atom" %}">{% trans "Atom" %}</a>
{% endif %}
{% endblock %}

templates/news.html
{% extends "base.html" %} {% block main %}
<div class="col-md-12 short_page">
    <h1>Coming Soon!</h1>
</div>
{% endblock %}

templates/submit_resume.html
{% extends "base.html" %} 
{% load i18n %} 
{% load account socialaccount %} 

{% block main %}

<div class="row short_page">
    <div class="col-md-offset-1 col-md-10">
        <h2 style="margin-bottom: 32px;">Submit Resume</h2> 
        <div class="col-md-12" id="div_signup_resume">
        <form class="form-horizontal" method="POST" enctype="multipart/form-data" onsubmit="submit_opsuser(event, this, 'resume')">
            {% csrf_token %}
            <input type="hidden" name="genre" value="resume">
            <div class="form-group">
                <label class="control-label col-sm-3" for="id_login">First Name:</label>
                <div class="col-sm-6">
                    <input autofocus="autofocus" name="first_name" placeholder="First Name" type="text" class="form-control" required="">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-3" for="id_login">Last Name:</label>
                <div class="col-sm-6">
                    <input autofocus="autofocus" name="last_name" placeholder="Last Name" type="text" class="form-control" required="">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-3" for="id_login">E-mail:</label>
                <div class="col-sm-6">
                    <input autofocus="autofocus" name="email" placeholder="E-mail address" type="email" class="form-control" required="">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-3" for="id_login">Years of Experience:</label>
                <div class="col-sm-6">
                    <input autofocus="autofocus" name="experience" placeholder="e.g. 3" type="number" class="form-control" required="">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-3" for="id_login">Zip Code:</label>
                <div class="col-sm-6">
                    <input autofocus="autofocus" name="zipcode" placeholder="Zip Code" type="text" class="form-control" required="">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-3" for="id_login">Phone:</label>
                <div class="col-sm-6">
                    <input autofocus="autofocus" name="phone" placeholder="Phone" type="phone" class="form-control" required="">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-3" for="id_password">Resume:</label>
                <div class="col-sm-6">
                    <input id="id_resume" name="resume" type="file" required>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-5">
                    <button type="submit" class="primaryAction btn btn-success">Submit</button>
                </div>
            </div>
            <div class="col-sm-offset-3 col-sm-8 error" id="div_error_signup_resume">
            </div>
        </form>
        </div>  
    </div>
</div>
{% endblock %}